repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace  # Removes trailing whitespace from all file types
      - id: end-of-file-fixer    # Ensures the file ends with a newline for all file types
      - id: check-yaml           # Checks YAML files for syntax errors and format issues
      - id: check-added-large-files  # Prevents adding large files to the repository

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.5.1
    hooks:
      - id: prettier
        files: \.(md|yaml|yml)$  # Formats Markdown, and YAML files
